version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - MySQL
      - Redis
      - Eclipse-mosquitto
    env_file: # TODO: 目前先使用.env文件，后续要使用Docker secrets！
      - .env
    ports:
      - "8080:8080"

  MySQL:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${Database_Password}
    ports:
      - "3306:3306"

  Redis:
    image: redis:latest
    environment:
      - REDIS_PASSWORD=${Redis_Password}
    ports:
      - "6379:6379"

  Eclipse-mosquitto:
    image: eclipse-mosquitto
    environment:
      - MOSQUITTO_USERNAME=${Mqtt_Username}
      - MOSQUITTO_PASSWORD=${Mqtt_Password}
    ports:
      - "1883:1883"

secrets:
  Aliyun_IP:
    external: true
  Redis_Password:
    external: true
  Database_User:
    external: true
  Database_Password:
    external: true
  Mosquitto_Username:
    external: true
  Mosquitto_Password:
    external: true
  Gmail_Username:
    external: true
  Gmail_App_Password:
    external: true
