spring:
  application:
    name: my-app

  # Alibaba MySQL DataSource
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${Aliyun_IP}:3306/myappDB
    username: ${Database_Username}
    password: ${Database_Password}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect # set MySQL8Dialect for MySQL 8.x

  # springSecurity
  security:
    user:
      name: admin
      password: admin

  # Redis
  data:
    redis:
      port: 6379
      host: ${Aliyun_IP}

  # use gmail to send email
  mail:
    default-encoding: utf-8
    host: smtp.gmail.com
    username: ${Gmail_Username}
    password: ${Gmail_App_Password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    port: 587


# MQTT
mqtt:
  broker: tcp://${Aliyun_IP}:1883
  clientId: MyMqttClient
  username: ${Mqtt_Username}
  password: ${Mqtt_Password}


# Mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml

# Logging
logging:
  file:
    name: logs/MyApp.log
  level:
    root: INFO
    com.demo.myapp: INFO