spring:
  application:
    name: my-app

  # Alibaba MySQL DataSource
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${Aliyun_IP}:3306/myappDB
    username: ${Database_Username}
    password: password: ${Database_Password}

  # springSecurity
  security:
    user:
      name: ${Security_Username}
      password: ${Security_Password}

  # Redis
  data:
    redis:
      port: 6379
      host: ${Aliyun_IP}

  # use gmail to send email
  mail:
    default-encoding: utf-8
    host: smtp.gmail.com
    username: ${Gmail_Username}
    password: ${Gmail_App_Password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    port: 587



# Mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml


