spring:
  application:
    name: my-app


  # Alibaba MySQL DataSource
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${Aliyun_IP}:3306/myappDB
    username: ${Database_Username}
    password: ${Database_Password}

  # springSecurity
  security:
    user:
      name: ${Security_Username}
      password: ${Security_Password}

#  Redis
  data:
    redis:
      port: 6379
      host: 120.25.104.84



