name: Alibaba Cloud CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.ALIYUN_SSH }}

      - name: Get Docker image tag
        id: get_tag
        run: echo "IMAGE_TAG=$(grep 'IMAGE_TAG' $GITHUB_ENV | cut -d'=' -f2)" >> $GITHUB_ENV


      - name: Deploy to Aliyun
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          ALIYUN_USER: ${{ secrets.ALIYUN_USER }}
          ALIYUN_IP: ${{ secrets.ALIYUN_IP }}
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
        run: |
          echo "Starting deployment..."

          # 登录Docker
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

          # 拉取最新的Docker镜像
          docker pull yupengli0106/myapp:${IMAGE_TAG}

          # SSH到服务器并部署
          ssh $ALIYUN_USER@$ALIYUN_IP << 'ENDSSH'
          docker stop my_app_container || true
          docker rm my_app_container || true
          docker run -d --name my_app_container -p 80:80 yupengli0106/myapp:${IMAGE_TAG}
          ENDSSH

          echo "Deployment finished."
