name: Alibaba Cloud CD

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.ALIYUN_SSH }}

      - name: Download artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: image-tag
          path: ./artifacts

      - name: Read image tag
        id: read_tag
        run: |
          IMAGE_TAG=$(cat ./artifacts/image_tag.txt)
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          echo "::set-output name=image_tag::$IMAGE_TAG"

      - name: Deploy to Aliyun
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          ALIYUN_USER: ${{ secrets.ALIYUN_USER }}
          ALIYUN_IP: ${{ secrets.ALIYUN_IP }}
          IMAGE_TAG: ${{ steps.read_tag.outputs.image_tag }}

        run: |
          echo "Starting deployment..."

          # 登录Docker
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

          # 拉取最新的Docker镜像
          docker pull yupengli0106/myapp:${IMAGE_TAG}

          # SSH到服务器并部署
          ssh $ALIYUN_USER@$ALIYUN_IP << 'ENDSSH'
          docker stop my_app_container || true
          docker rm my_app_container || true
          docker run -d --name my_app_container -p 80:80 yupengli0106/myapp:${IMAGE_TAG}
          ENDSSH

          echo "Deployment finished."
