name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.7

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3.1.0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.4.0

    - name: Login to Docker Hub
      uses: docker/login-action@v3.2.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6.4.0
      with:
        context: .
        push: true
        tags: yupengli0106/myapp:$(date +%s)


    - name: Log out from Docker Hub
      run: docker logout
