name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.7

    #设置环境变量（当前的系统时间）
    - name: Set current date as environment variable
      id: date
      run: echo "date=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

    #兼容可以在不同的操作系统环境中运行
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3.1.0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.4.0

    - name: Login to Docker Hub
      uses: docker/login-action@v3.2.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    #构建镜像并且push到Docker Hub的yupengli0106/myapp这个仓库下
    - name: Build and push Docker image
      uses: docker/build-push-action@v6.4.0
      with:
        context: .
        push: true
        tags: yupengli0106/myapp:MyApp-${{ env.date }}

    #输出当前打包好的镜像给下一步的CD用来部署
    - name: Set docker image output
      id: image_tag
      run: |
        echo "IMAGE_TAG=MyApp-${{ env.date }}" >> $GITHUB_ENV
        echo "IMAGE_TAG=MyApp-${{ env.date }}" > image_tag.txt

    - name: Upload artifact
      uses: actions/upload-artifact@v4.3.4
      with:
        name: image-tag
        path: image_tag.txt

    - name: Log out from Docker Hub
      run: docker logout
